### ISSUE TITLE
exclusion is too agressive

### ISSUE THREAD

**Issue by timothypratley** [cldwalker/smart-ignore#1] opened 2014-03-10 13:50 UTC
Great plugin - unfortunately it hides all directories in my workspace folders.  Doubtless this is due to my .gitignore_global. I suspect
*~
is what is tripping it up

**Comment by cldwalker** [comment] 2014-03-10 16:50
This issue can't be due to your global gitignore, since smart-ignore [only looks in .gitignore](https://github.com/cldwalker/smart-ignore/blob/master/src/lt/plugins/smart_ignore.cljs#L23).
Could you provide a means of reproducing this? At a minimum this mean your .gitignore and your git repo. If you can't provide the git repo, then a list of all directories and the list of ones being hidden

**Comment by timothypratley** [comment] 2014-03-11 04:10
Strangely I get the behavior without any .gitignore at all...
I created a new folder, created a file under it.
I could see the file in workspace.
Restarted Lighttable
and cannot open the folder in workspace tree.
The actual search itself is great.
This is on a Mac
I'll get you some better information on the weekend by adding some printlns around

**Comment by cldwalker** [comment] 2014-03-16 14:36
I've pushed 0.1.1 which solved aggressive exclusion as reported in #2. I'm closing this for now. If it's still an issue, feel free to add a reproducible bug report and I can reopen.

**Closed as completed by cldwalker** 2014-03-16 14:36 UTC
